### ISSUE TITLE
PXD-1809 ⁃ allow props to be object

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/tube#12]
allow the etl to rename a field:
```
_props:
  - name: prop
  - name: property_name_in_es
    source(optional, default to name): property_name_in_psqlgraph
```
allow the etl to rename a value:
```
_props:
  - name: property_name_in_es
    source: property_name_in_psqlgraph
    value_mapping:
      "Positive": Yes
      "Negative": No
```
