### ISSUE TITLE
PXD-1821 ⁃ allow flatten props to do path traversal too

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/tube#22]
```
  _flatten_props:
    - path: edge1.edge2
      _props:
        - prop
```
if the child > 1 during mapreduce , just get the first 1
